# generated by Django 4.1.1 on 2022-10-10 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('left_neighbor', models.CharField(max_length=128)),
                ('right_neighbor', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('calories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodrle.calories')),
                ('colors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodrle.colors')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodrle.country')),
            ],
        ),
        migrations.CreateModel(
            name='MainIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('food_group', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweet', models.BooleanField()),
                ('salty', models.BooleanField()),
                ('sour', models.BooleanField()),
                ('bitter', models.BooleanField()),
                ('umami', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_streak', models.BigIntegerField()),
                ('max_streak', models.BigIntegerField()),
                ('last_played', models.DateField()),
                ('games_played', models.BigIntegerField()),
                ('win_1', models.IntegerField()),
                ('win_2', models.IntegerField()),
                ('win_3', models.IntegerField()),
                ('win_4', models.IntegerField()),
                ('win_5', models.IntegerField()),
                ('win_6', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.DateField()),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodrle.dishes')),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='main_ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodrle.mainingredient'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='taste_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodrle.taste'),
        ),
    ]
