# Generated by Django 4.1.1 on 2022-10-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='curr_streak',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='games_played',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='max_streak',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='win_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='win_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='win_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='win_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='win_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='win_6',
            field=models.IntegerField(default=0),
        ),
    ]
