# Generated by Django 4.1.1 on 2022-10-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='dish_id',
            new_name='dish',
        ),
    ]
