# Generated by Django 4.1.1 on 2022-10-23 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrle', '0002_alter_userstats_curr_streak_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='main_ingredient_id',
            new_name='main_ingredient',
        ),
        migrations.RenameField(
            model_name='dishes',
            old_name='taste_id',
            new_name='taste',
        ),
        migrations.RenameField(
            model_name='puzzle',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='userstats',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='colors_id',
        ),
        migrations.AlterField(
            model_name='dishes',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainingredient',
            name='food_group',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Calories',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
