# Generated by Django 4.1.1 on 2022-10-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrle', '0003_rename_country_id_dishes_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='calories',
            field=models.BigIntegerField(default=0),
        ),
    ]
