# Generated by Django 4.1.1 on 2022-10-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrle', '0003_alter_mainingredient_food_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='color',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
