# Generated by Django 4.1.1 on 2022-11-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrle', '0006_rename_dish_puzzle_ans_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
