# Generated by Django 4.1.1 on 2022-11-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrle', '0008_puzzle_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
    ]
