# Generated by Django 4.1.1 on 2022-11-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrle', '0009_puzzle_is_win'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
