version: "3.9"
services:
  db:
    build: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
  app:
    build: app
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_EMAIL=dummyemail@example.com
      - DJANGO_SECRET_KEY=django-insecure-v9@wclex#ifim9k4)8_=+hoaf6+hx=8x7+8ibioay30adu1y+n
    depends_on:
      - db
    networks:
      - backend
  web:
    build: web
    volumes:
      - ./web/config/nginx.conf:/etc/nginx/nginx.conf
      - ./web/config/conf.d:/etc/nginx/conf.d
      - ./web/static:/usr/share/nginx/html/static
    ports:
      - "80:80"
    depends_on:
      - db
      - app
    networks:
      - backend
networks:
  backend: